backend:
  name: github
  repo: xuan-0717/blog
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime", format: "YYYY-MM-DDTHH:mm:ss+08:00", date_format: "YYYY-MM-DD", time_format: "HH:mm"}
      - {label: "草稿", name: "draft", widget: "boolean", default: true}
      - {label: "标签", name: "tags", widget: "list"}
      - {label: "分类", name: "categories", widget: "list"}
      - {label: "正文", name: "body", widget: "markdown"}
